
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class panel extends javax.swing.JPanel {

    /**
     * Creates new form panel
     */
    public JScrollPane pane ;
    GraphPanel gp;
    
    public panel(GraphPanel g) {
        initComponents();
        gp=g;
             Protein[] arr=gp.x;
        for(int i=0;i<arr.length;i++){
            cboxProtein.addItem(arr[i].seq_id);
        }
    }

    panel(GraphPanel g, BorderLayout borderLayout) {
        initComponents();
        gp=g;
             Protein[] arr=gp.x;
        for(int i=0;i<arr.length;i++){
            cboxProtein.addItem(arr[i].seq_id);
        }
        String[][] addressData = {{"a","b","c","d"},{"e","f","g","h"}};
      DefaultTableModel model=new DefaultTableModel(addressData,new String[]{"Acc No","PI","MW","Description"});
      JTable tblInteraction=new JTable(model);
      this.add(tblInteraction);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSelectProtein = new javax.swing.JLabel();
        cboxProtein = new javax.swing.JComboBox();
        btnGetInteraction = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbSelectProtein.setText("Select Protein");

        cboxProtein.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        btnGetInteraction.setText("Get Interaction");
        btnGetInteraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetInteractionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbSelectProtein, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboxProtein, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGetInteraction)
                .addGap(468, 468, 468))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSelectProtein)
                    .addComponent(cboxProtein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetInteraction))
                .addContainerGap(454, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetInteractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetInteractionActionPerformed
        // TODO add your handling code here:
        String value=cboxProtein.getSelectedItem().toString();
      ppi.Node n=gp.nt.getNode(value);
        System.out.println("IN button selected Protein is :"+n.getAccNo());
   

   String[][] addressData = {{"a","b","c","d"},{"e","f","g","h"}};
      DefaultTableModel model=new DefaultTableModel(addressData,new String[]{"Acc No","PI","MW","Description"});
      JTable tblInteraction=new JTable(model);
      //model.addColumn("Acc NO");
      //model.addColumn("PI");
     // model.addColumn("MW");
     // model.addColumn("Description")kro;
    //  tblInteraction.setModel(model);
      System.out.println("Showing jtable--------------------------------");
      tblInteraction.setBounds(130, 40, 200, 200);
      tblInteraction.setPreferredScrollableViewportSize(new Dimension(300,400));
    tblInteraction.setFillsViewportHeight(true);
      tblInteraction.setVisible(true);
       pane = new JScrollPane(tblInteraction,JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
      pane.setVisible(true);
      this.add(pane,BorderLayout.CENTER);
      
    }//GEN-LAST:event_btnGetInteractionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetInteraction;
    private javax.swing.JComboBox cboxProtein;
    private javax.swing.JLabel lbSelectProtein;
    // End of variables declaration//GEN-END:variables
}
